[package]
name = "misskey-3ds"
version = "0.1.0"
edition = "2021"

[dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
static-toml = "1.2.0"

[package.metadata.cargo-3ds]
romfs_dir = "romfs"
