token = "" # Put your API key here
host = "example.com" # Put the hostname of the instance you're connecting to here
port = 80 # Put the port of the API here. We don't support HTTPS yet so it's probably 80
